#!/usr/bin/env python
if __name__ == "__main__":
    import sys
    import pyrit_cli
    try:
        pyrit_cli.Pyrit_CLI().initFromArgv()
    except (KeyboardInterrupt, SystemExit):
        print("Interrupted...", file=sys.stderr)
    except pyrit_cli.PyritRuntimeError as e:
        sys.exit(e)
