#!/usr/bin/env python
if __name__ == "__main__":
    import pyrit_cli
    import sys
    try:
        pyrit_cli.Pyrit_CLI().initFromArgv()
    except (pyrit_cli.PyritRuntimeError, KeyboardInterrupt, SystemExit), e:
        sys.exit(e)

